### PR TITLE
CAN library Mainboard

### PR DESCRIPTION
**Pull request by Disteroas**
We think that we've completed CAN protocol library for the mainboard. CAN you please check what we've done? (We probably made 200 errors)

### CODE REVIEW

**Review by luca-byte — COMMENTED** [review]
Ok, great start! 💯 
There are just some small questions/problems:
1. The comments are in italian
2. There is a lot of confusion in the methods (we receive setpoints and send feedback and I do not understand why you have chosen to do these choices as methods)
3. The library (as of now) is not testable or compilable (the library is missing and there is no .ino file to test it with). 
4. The initial configuration of the CAN is completely missing
5. Why are you including the ` <cstring>`  header file?

In brief I am unable to grasp many of your design choices. Would you mind explaining to me why have you decided to do the library in this way.

**Comment by luca-byte** [comment]
@m4r14g What are your thoughts?

**Comment by m4r14g** [comment]
I just reviewed what has been done. This is a good starting point, however I agree with Luca's observations. I need also to point out a mismatch between the methods and datatypes used (theoretically coming from the 2 mentioned libraries) and the actual libraries' ones. I’m referring to CAN_write(), CAN_read(), CAN_init(), and can_frame_t.

**Comment by Pitosoro** [comment]
ok I made some fixes (I hope there are less errors than before)

- the distinction between sending setpoints and receiving feedback should be fixed: sendMotorSetpoint and sendEndEffectorSetpoint send commands while receiveMotorFeedback and receiveEndEffectorSetpoint receive data.
- I added the initial configuration of the CAN
- as someone suggested me (you can guess who or what) I kept the cstring library to use memcpy which is more efficient for copying data into CAN frames

there is still no .ino file, i will do it later

**Pull request closed without merging**
